# Generated by Django 5.2.12 on 2026-04-02 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_ptr', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='admin_profile', serialize=False, to='users.user')),
            ],
            options={
                'db_table': 'admins',
            },
            bases=('users.user',),
        ),
    ]
