version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: bd
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bd"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: django_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_users &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
<<<<<<< HEAD
      - STRIPE_PUBLIC_KEY=pk_test_51TMBBhPXiqFPh33KyIbsOZ8RsfHSKetZUlDw5TcJGplqiu1CCbj3j6juXYlw8q1I6URGhRQYxq0WVPngtdDPBUJT001RIElCvc
      - STRIPE_SECRET_KEY=sk_test_51TMBBhPXiqFPh33KIxYKzdqGJV84NXZXOS03l5ZZQRnfW7EwVpM43cOUXH619ntjUGVkfxrorw1wemOYkQwxtOMs00LeexEL26
=======
>>>>>>> 0796e1801988747f1e405605aa5bfaca0941b2f5
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: