# Generated by Django 6.0.3 on 2026-04-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('refuel', '0001_initial'),
        ('shift', '0001_initial'),
        ('taxi', '0006_taxi_consumo_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='refuel',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuels', to='shift.shift'),
        ),
        migrations.AddField(
            model_name='refuel',
            name='taxi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuels', to='taxi.taxi'),
        ),
    ]
