# Generated by Django 6.0.3 on 2026-05-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refuel',
            name='kms_previos',
        ),
        migrations.RemoveField(
            model_name='refuel',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='refuel',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='refuel',
            name='euros_pagos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refuel',
            name='kms_taxi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refuel',
            name='kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refuel',
            name='litros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
