# Generated by Django 6.0.3 on 2026-03-29 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_taxi_marca_conforto_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi',
            name='id_taxi',
        ),
        migrations.AddField(
            model_name='taxi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='nivel_conforto',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='taxi',
            table=None,
        ),
    ]
