# Generated by Django 6.0.3 on 2026-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_remove_taxi_id_taxi_taxi_id_alter_taxi_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='nivel_conforto',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Conforto', 'Conforto'), ('Premium', 'Premium')], max_length=20),
        ),
    ]
