# Generated by Django 6.0.3 on 2026-03-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_alter_taxi_nivel_conforto'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='tipo_motor',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Elétrico', 'Elétrico'), ('Híbrido', 'Híbrido')], default='Gasolina', max_length=50),
        ),
    ]
