# Generated by Django 6.0.3 on 2026-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_taxi_tipo_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='consumo_medio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
