# Generated by Django 6.0.4 on 2026-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0007_taxi_estado_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='nivel_conforto',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Luxuoso', 'Luxuoso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='tipo_motor',
            field=models.CharField(choices=[('Combustão', 'Combustão'), ('Elétrico', 'Elétrico')], default='Combustão', max_length=50),
        ),
    ]
