# Generated by Django 6.0.5 on 2026-06-01 13:31

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0008_alter_taxi_nivel_conforto_alter_taxi_tipo_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco_basico_minuto', models.DecimalField(decimal_places=2, default=Decimal('0.25'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('preco_luxuoso_minuto', models.DecimalField(decimal_places=2, default=Decimal('0.40'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('agravamento_noturno_percentual', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
