# Generated by Django 6.0.5 on 2026-06-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0009_pricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
