# Generated by Django 6.0.3 on 2026-03-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxis', '0001_initial'),
        ('users', '0005_alter_admin_user_ptr_alter_client_user_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='driver', serialize=False, to='users.user')),
                ('ano_nascimento', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('Outro', 'Outro')], max_length=5)),
                ('num_carta_conducao', models.CharField(max_length=50, unique=True)),
                ('localidade', models.CharField(max_length=150)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'motoristas',
            },
            bases=('users.user',),
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
    ]
