# Generated by Django 6.0.3 on 2026-05-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_driver_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=5),
        ),
    ]
