# Generated by Django 6.0.4 on 2026-04-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('taxi', '0007_taxi_estado_latitude_longitude'),
        ('trip', '0002_trip_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='driver.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='taxi.taxi'),
        ),
    ]
