# Generated by Django 6.0.4 on 2026-04-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_driver_alter_trip_taxi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
