# Generated by Django 6.0.4 on 2026-04-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='nivel_conforto',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Conforto', 'Conforto'), ('Premium', 'Premium')], default='Standard', max_length=20),
        ),
    ]
