# Generated by Django 6.0.5 on 2026-05-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_nivel_conforto'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rejected_driver_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='trip',
            name='nivel_conforto',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Luxuoso', 'Luxuoso')], default='Standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status_trip',
            field=models.CharField(choices=[('pending', 'Pending'), ('driver_accepted', 'Driver Accepted'), ('client_confirmed', 'Client Confirmed'), ('in_progress', 'In Progress'), ('awaiting_payment', 'Awaiting Payment'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
