# Generated by Django 6.0.3 on 2026-03-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin_client_subtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='user_ptr',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='admin_profile', serialize=False, to='users.user'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_ptr',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='client_profile', serialize=False, to='users.user'),
        ),
    ]
