# Generated by Django 6.0.3 on 2026-05-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ano',
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='n_fatura',
            field=models.PositiveIntegerField(),
        ),
    ]
