# Generated by Django 6.0.5 on 2026-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_ano_alter_invoice_n_fatura'),
        ('trip', '0006_trip_rejected_driver_ids_alter_trip_nivel_conforto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.51, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('n_fatura', 'ano'), name='unique_invoice_number_per_year'),
        ),
    ]
